// Regenerate src/catalog.ts from pi's Anthropic model catalog (run after bumping pi).
// The extension cannot import pi-ai subpaths at runtime: pi's loader aliases only package roots.
import { writeFileSync } from "node:fs";
import { ANTHROPIC_MODELS } from "@earendil-works/pi-ai/providers/anthropic.models";

const models = Object.values(ANTHROPIC_MODELS)
	.filter((m) => !/-\d{8}$/.test(m.id))
	.map(({ id, name, reasoning, input, cost, contextWindow, maxTokens, thinkingLevelMap }) => ({ id, name, reasoning, input, cost, contextWindow, maxTokens, ...(thinkingLevelMap ? { thinkingLevelMap } : {}) }));
writeFileSync(
	new URL("../src/catalog.ts", import.meta.url),
	`// Generated by scripts/gen-catalog.mjs from pi's Anthropic catalog. Do not edit.\nexport const CATALOG = ${JSON.stringify(models, null, "\t")} as const;\n`,
);
console.log(`wrote ${models.length} models`);
