// Generated by scripts/gen-catalog.mjs from pi's Anthropic catalog. Do not edit.
export const CATALOG = [
	{
		"id": "claude-fable-5",
		"name": "Claude Fable 5",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 10,
			"output": 50,
			"cacheRead": 1,
			"cacheWrite": 12.5
		},
		"contextWindow": 1000000,
		"maxTokens": 128000,
		"thinkingLevelMap": {
			"off": null,
			"xhigh": "xhigh",
			"max": "max"
		}
	},
	{
		"id": "claude-fable-5-1",
		"name": "Claude Fable 5.1",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 10,
			"output": 50,
			"cacheRead": 0.25,
			"cacheWrite": 12.5
		},
		"contextWindow": 1000000,
		"maxTokens": 128000,
		"thinkingLevelMap": {
			"off": null,
			"xhigh": "xhigh",
			"max": "max"
		}
	},
	{
		"id": "claude-haiku-4-5",
		"name": "Claude Haiku 4.5 (latest)",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 1,
			"output": 5,
			"cacheRead": 0.1,
			"cacheWrite": 1.25
		},
		"contextWindow": 200000,
		"maxTokens": 64000
	},
	{
		"id": "claude-opus-4-5",
		"name": "Claude Opus 4.5 (latest)",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 5,
			"output": 25,
			"cacheRead": 0.5,
			"cacheWrite": 6.25
		},
		"contextWindow": 200000,
		"maxTokens": 64000
	},
	{
		"id": "claude-opus-4-6",
		"name": "Claude Opus 4.6",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 5,
			"output": 25,
			"cacheRead": 0.5,
			"cacheWrite": 6.25
		},
		"contextWindow": 1000000,
		"maxTokens": 128000,
		"thinkingLevelMap": {
			"max": "max"
		}
	},
	{
		"id": "claude-opus-4-7",
		"name": "Claude Opus 4.7",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 5,
			"output": 25,
			"cacheRead": 0.5,
			"cacheWrite": 6.25
		},
		"contextWindow": 1000000,
		"maxTokens": 128000,
		"thinkingLevelMap": {
			"xhigh": "xhigh",
			"max": "max"
		}
	},
	{
		"id": "claude-opus-4-8",
		"name": "Claude Opus 4.8",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 5,
			"output": 25,
			"cacheRead": 0.5,
			"cacheWrite": 6.25
		},
		"contextWindow": 1000000,
		"maxTokens": 128000,
		"thinkingLevelMap": {
			"xhigh": "xhigh",
			"max": "max"
		}
	},
	{
		"id": "claude-opus-5",
		"name": "Claude Opus 5",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 5,
			"output": 25,
			"cacheRead": 0.5,
			"cacheWrite": 6.25
		},
		"contextWindow": 1000000,
		"maxTokens": 128000,
		"thinkingLevelMap": {
			"off": null,
			"xhigh": "xhigh",
			"max": "max"
		}
	},
	{
		"id": "claude-opus-5-5",
		"name": "Claude Opus 5.5",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 4,
			"output": 20,
			"cacheRead": 0.2,
			"cacheWrite": 5
		},
		"contextWindow": 1000000,
		"maxTokens": 128000,
		"thinkingLevelMap": {
			"off": null,
			"minimal": null,
			"low": "low",
			"medium": "medium",
			"high": "high",
			"xhigh": "xhigh",
			"max": "max"
		}
	},
	{
		"id": "claude-sonnet-4-5",
		"name": "Claude Sonnet 4.5 (latest)",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 3,
			"output": 15,
			"cacheRead": 0.3,
			"cacheWrite": 3.75
		},
		"contextWindow": 1000000,
		"maxTokens": 64000
	},
	{
		"id": "claude-sonnet-4-6",
		"name": "Claude Sonnet 4.6",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 3,
			"output": 15,
			"cacheRead": 0.3,
			"cacheWrite": 3.75
		},
		"contextWindow": 1000000,
		"maxTokens": 128000,
		"thinkingLevelMap": {
			"max": "max"
		}
	},
	{
		"id": "claude-sonnet-5",
		"name": "Claude Sonnet 5",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 2,
			"output": 10,
			"cacheRead": 0.2,
			"cacheWrite": 2.5
		},
		"contextWindow": 1000000,
		"maxTokens": 128000,
		"thinkingLevelMap": {
			"xhigh": "xhigh",
			"max": "max"
		}
	},
	{
		"id": "claude-sonnet-5-5",
		"name": "Claude Sonnet 5.5",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 2,
			"output": 10,
			"cacheRead": 0.2,
			"cacheWrite": 2.5
		},
		"contextWindow": 1000000,
		"maxTokens": 128000,
		"thinkingLevelMap": {
			"off": null,
			"minimal": null,
			"low": "low",
			"medium": "medium",
			"high": "high",
			"xhigh": "xhigh",
			"max": "max"
		}
	}
] as const;
